SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CATEGORIA` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`CATEGORIA` (
  `ID_CATEGORIA` INT NOT NULL AUTO_INCREMENT ,
  `NOMBRE` VARCHAR(45) NOT NULL ,
  `DESCRIPCION` VARCHAR(45) NULL ,
  `STATUS` TINYINT(1) NOT NULL DEFAULT 1 ,
  PRIMARY KEY (`ID_CATEGORIA`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAIS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PAIS` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`PAIS` (
  `ID_PAIS` INT NULL ,
  `NOMBRE` VARCHAR(45) NULL ,
  `STATUS` TINYINT(1) NULL ,
  PRIMARY KEY (`ID_PAIS`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ESTADO` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`ESTADO` (
  `ID_ESTADO` INT NOT NULL ,
  `NOMBRE` VARCHAR(45) NOT NULL ,
  `ID_PAIS` INT NOT NULL ,
  `STATUS` TINYINT(1) NULL ,
  PRIMARY KEY (`ID_ESTADO`) ,
  INDEX `FK_PAIS_idx` (`ID_PAIS` ASC) ,
  CONSTRAINT `FK_PAIS`
    FOREIGN KEY (`ID_PAIS` )
    REFERENCES `mydb`.`PAIS` (`ID_PAIS` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOCALIDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LOCALIDAD` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`LOCALIDAD` (
  `ID_LOCALIDAD` INT NOT NULL ,
  `NOMBRE` VARCHAR(45) NOT NULL ,
  `ID_ESTADO` INT NOT NULL ,
  `STATUS` TINYINT(1) NULL ,
  PRIMARY KEY (`ID_LOCALIDAD`) ,
  INDEX `FK_ESTADO_idx` (`ID_ESTADO` ASC) ,
  CONSTRAINT `FK_ESTADO`
    FOREIGN KEY (`ID_ESTADO` )
    REFERENCES `mydb`.`ESTADO` (`ID_ESTADO` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CODIGO_POSTAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CODIGO_POSTAL` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`CODIGO_POSTAL` (
  `ID_CODIGO_POSTAL` INT NOT NULL ,
  `NUMERO` INT(5) NOT NULL ,
  `ID_LOCALIDAD` INT NOT NULL ,
  `STATUS` TINYINT(1) NOT NULL ,
  PRIMARY KEY (`ID_CODIGO_POSTAL`) ,
  INDEX `FK_LOCALIDAD_idx` (`ID_LOCALIDAD` ASC) ,
  CONSTRAINT `FK_LOCALIDAD`
    FOREIGN KEY (`ID_LOCALIDAD` )
    REFERENCES `mydb`.`LOCALIDAD` (`ID_LOCALIDAD` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COLONIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COLONIA` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`COLONIA` (
  `ID_COLONIA` INT NOT NULL ,
  `NOMBRE` VARCHAR(45) NOT NULL ,
  `ID_CODIGO_POSTAL` INT NOT NULL ,
  `STATUS` TINYINT(1) NOT NULL ,
  PRIMARY KEY (`ID_COLONIA`) ,
  INDEX `FK_CP_idx` (`ID_CODIGO_POSTAL` ASC) ,
  CONSTRAINT `FK_CP`
    FOREIGN KEY (`ID_CODIGO_POSTAL` )
    REFERENCES `mydb`.`CODIGO_POSTAL` (`ID_CODIGO_POSTAL` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROPIEDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PROPIEDAD` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`PROPIEDAD` (
  `ID_PROPIEDAD` INT NOT NULL AUTO_INCREMENT ,
  `NOMBRE` VARCHAR(45) NOT NULL ,
  `DESCRIPCION` VARCHAR(450) NOT NULL ,
  `EXTENSION` INT NULL ,
  `NO_BANIOS` INT(5) NULL ,
  `NO_HABITACIONES` INT(5) NULL ,
  `NO_PISOS` INT(5) NULL ,
  `COLOR_1` VARCHAR(45) NULL DEFAULT 'NA' ,
  `COLOR_2` VARCHAR(45) NULL DEFAULT 'NA' ,
  `FECHA_CONSTRUCCION` DATE NULL ,
  `TIPO_FACHADA` VARCHAR(45) NULL DEFAULT 'NA' ,
  `THUMBNAIL` VARCHAR(450) NULL ,
  `CALLE` VARCHAR(45) NOT NULL ,
  `NO_EXTERIOR` VARCHAR(45) NOT NULL ,
  `NO_INTERIOR` VARCHAR(45) NULL ,
  `ID_COLONIA` INT NOT NULL ,
  `ID_CATEGORIA` INT NOT NULL ,
  `STATUS` TINYINT(1) NOT NULL DEFAULT 1 ,
  PRIMARY KEY (`ID_PROPIEDAD`) ,
  INDEX `FK_CATEGORIA_idx` (`ID_CATEGORIA` ASC) ,
  UNIQUE INDEX `ID_PROPIEDAD_UNIQUE` (`ID_PROPIEDAD` ASC) ,
  INDEX `FK_COLONIA_PROPIEDAD_idx` (`ID_COLONIA` ASC) ,
  CONSTRAINT `FK_CATEGORIA`
    FOREIGN KEY (`ID_CATEGORIA` )
    REFERENCES `mydb`.`CATEGORIA` (`ID_CATEGORIA` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COLONIA_PROPIEDAD`
    FOREIGN KEY (`ID_COLONIA` )
    REFERENCES `mydb`.`COLONIA` (`ID_COLONIA` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USUARIO` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT ,
  `NOMBRE_USUARIO` VARCHAR(45) NOT NULL ,
  `CONTRASENIA` VARCHAR(45) NOT NULL ,
  `NOMBRE` VARCHAR(45) NOT NULL ,
  `AP_PAT` VARCHAR(45) NOT NULL ,
  `AP_MAT` VARCHAR(45) NOT NULL ,
  `TELEFONO` VARCHAR(45) NOT NULL ,
  `EMAIL` VARCHAR(45) NOT NULL ,
  `FECHA_NACIMIENTO` DATE NOT NULL ,
  `RFC` VARCHAR(45) NULL ,
  `CURP` VARCHAR(45) NULL ,
  `TIPO_USUARIO` VARCHAR(45) NOT NULL ,
  `CALLE` VARCHAR(45) NOT NULL ,
  `NO_EXTERIOR` VARCHAR(45) NOT NULL ,
  `NO_INTERIOR` VARCHAR(45) NULL ,
  `ID_COLONIA` INT NOT NULL ,
  `STATUS` TINYINT(1) NOT NULL DEFAULT 1 ,
  PRIMARY KEY (`ID_USUARIO`) ,
  INDEX `FK_COLONIA_USUARIO_idx` (`ID_COLONIA` ASC) ,
  CONSTRAINT `FK_COLONIA_USUARIO`
    FOREIGN KEY (`ID_COLONIA` )
    REFERENCES `mydb`.`COLONIA` (`ID_COLONIA` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONTRATO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CONTRATO` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`CONTRATO` (
  `ID_CONTRATO` INT NOT NULL AUTO_INCREMENT ,
  `FECHA` DATE NOT NULL ,
  `DESCRIPCION` VARCHAR(4500) NOT NULL ,
  `ID_PROPIEDAD` INT NOT NULL ,
  `ID_USUARIO` INT NOT NULL ,
  `STATUS` TINYINT(1) NULL ,
  PRIMARY KEY (`ID_CONTRATO`) ,
  INDEX `PK_PROPIEDAD_idx` (`ID_PROPIEDAD` ASC) ,
  INDEX `PK_USUARIO_idx` (`ID_USUARIO` ASC) ,
  CONSTRAINT `PK_PROPIEDAD`
    FOREIGN KEY (`ID_PROPIEDAD` )
    REFERENCES `mydb`.`PROPIEDAD` (`ID_PROPIEDAD` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PK_USUARIO`
    FOREIGN KEY (`ID_USUARIO` )
    REFERENCES `mydb`.`USUARIO` (`ID_USUARIO` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PAGO` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`PAGO` (
  `ID_PAGO` INT NOT NULL AUTO_INCREMENT ,
  `DESCRIPCION` VARCHAR(45) NOT NULL ,
  `MONTO` DECIMAL(10,2) NOT NULL ,
  `STATUS` TINYINT(1) NOT NULL DEFAULT 1 ,
  PRIMARY KEY (`ID_PAGO`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REGISTRO_PAGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`REGISTRO_PAGO` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`REGISTRO_PAGO` (
  `ID_REGISTRO_PAGO` INT NOT NULL AUTO_INCREMENT ,
  `F_INICIO` DATE NULL ,
  `F_VENCIMIENTO` DATE NULL ,
  `ID_CONTRATO` INT NOT NULL ,
  `ID_PAGO` INT NOT NULL ,
  `STATUS` TINYINT(1) NOT NULL DEFAULT 1 ,
  PRIMARY KEY (`ID_REGISTRO_PAGO`) ,
  INDEX `PK_CONTRATO_idx` (`ID_CONTRATO` ASC) ,
  INDEX `PK_PAGO_idx` (`ID_PAGO` ASC) ,
  CONSTRAINT `PK_CONTRATO`
    FOREIGN KEY (`ID_CONTRATO` )
    REFERENCES `mydb`.`CONTRATO` (`ID_CONTRATO` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PK_PAGO`
    FOREIGN KEY (`ID_PAGO` )
    REFERENCES `mydb`.`PAGO` (`ID_PAGO` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`DISENIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DISENIO` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`DISENIO` (
  `ID_DISENIO` INT NOT NULL AUTO_INCREMENT ,
  `RUTA` VARCHAR(150) NOT NULL ,
  `RUTA_SKYBOX` VARCHAR(150) NULL ,
  `ID_USUARIO` INT NULL ,
  `ID_PROPIEDAD` INT NOT NULL ,
  `STATUS` TINYINT(1) NULL ,
  PRIMARY KEY (`ID_DISENIO`) ,
  INDEX `PK_PROPERTY_idx` (`ID_PROPIEDAD` ASC) ,
  CONSTRAINT `PK_PROPERTY`
    FOREIGN KEY (`ID_PROPIEDAD` )
    REFERENCES `mydb`.`PROPIEDAD` (`ID_PROPIEDAD` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MENSAJE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MENSAJE` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`MENSAJE` (
  `ID_MENSAJE` INT NOT NULL ,
  `ID_REMITENTE` INT NOT NULL ,
  `ID_DESTINATARIO` INT NOT NULL ,
  `MENSAJE` VARCHAR(450) NOT NULL ,
  `STATUS_LEIDO` TINYINT(1) NULL ,
  `ID_PROPIEDAD` INT NULL ,
  `STATUS` TINYINT(1) NULL DEFAULT 1 ,
  PRIMARY KEY (`ID_MENSAJE`) ,
  INDEX `ID_REMITENTE_idx` (`ID_REMITENTE` ASC) ,
  INDEX `ID_DESTINATARIO_idx` (`ID_DESTINATARIO` ASC) ,
  CONSTRAINT `ID_REMITENTE`
    FOREIGN KEY (`ID_REMITENTE` )
    REFERENCES `mydb`.`USUARIO` (`ID_USUARIO` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_DESTINATARIO`
    FOREIGN KEY (`ID_DESTINATARIO` )
    REFERENCES `mydb`.`USUARIO` (`ID_USUARIO` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FAVORITO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FAVORITO` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`FAVORITO` (
  `ID_FAVORITO` INT NOT NULL ,
  `ID_USUARIO` INT NOT NULL ,
  `ID_PROPIEDAD` INT NOT NULL ,
  `NO_ESTRELLAS` INT NULL ,
  PRIMARY KEY (`ID_FAVORITO`) ,
  INDEX `ID_USUARIO_idx` (`ID_USUARIO` ASC) ,
  INDEX `ID_PROPIEDAD_idx` (`ID_PROPIEDAD` ASC) ,
  CONSTRAINT `ID_USUARIO`
    FOREIGN KEY (`ID_USUARIO` )
    REFERENCES `mydb`.`USUARIO` (`ID_USUARIO` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_PROPIEDAD`
    FOREIGN KEY (`ID_PROPIEDAD` )
    REFERENCES `mydb`.`PROPIEDAD` (`ID_PROPIEDAD` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HISTORIAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HISTORIAL` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`HISTORIAL` (
  `ID_HISTORIAL` INT NOT NULL ,
  `ID_USUARIO` INT NOT NULL ,
  `ID_PROPIEDAD` INT NOT NULL ,
  `FECHA` DATE NOT NULL ,
  PRIMARY KEY (`ID_HISTORIAL`) ,
  INDEX `ID_USUARIO_idx` (`ID_USUARIO` ASC) ,
  INDEX `ID_PROPIEDAD_idx` (`ID_PROPIEDAD` ASC) ,
  CONSTRAINT `ID_USUARIO`
    FOREIGN KEY (`ID_USUARIO` )
    REFERENCES `mydb`.`USUARIO` (`ID_USUARIO` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_PROPIEDAD`
    FOREIGN KEY (`ID_PROPIEDAD` )
    REFERENCES `mydb`.`PROPIEDAD` (`ID_PROPIEDAD` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DISENIADOR_PROPIEDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DISENIADOR_PROPIEDAD` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`DISENIADOR_PROPIEDAD` (
  `ID_DISENIADOR_PROPIEDAD` INT NOT NULL ,
  `ID_USUARIO` INT NOT NULL ,
  `ID_DISENIO` INT NOT NULL ,
  PRIMARY KEY (`ID_DISENIADOR_PROPIEDAD`) ,
  INDEX `FK_USR_DISENIADOR_idx` (`ID_USUARIO` ASC) ,
  INDEX `FK_PROP_DISENIADOR_idx` (`ID_DISENIO` ASC) ,
  CONSTRAINT `FK_USR_DISENIADOR`
    FOREIGN KEY (`ID_USUARIO` )
    REFERENCES `mydb`.`USUARIO` (`ID_USUARIO` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROP_DISENIADOR`
    FOREIGN KEY (`ID_DISENIO` )
    REFERENCES `mydb`.`DISENIO` (`ID_DISENIO` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATALOGO_FOTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CATALOGO_FOTOS` ;

CREATE  TABLE IF NOT EXISTS `mydb`.`CATALOGO_FOTOS` (
  `ID_CATALOGO_FOTOS` INT NOT NULL ,
  `RUTA_FOTOGRAFIA` VARCHAR(150) NOT NULL ,
  `DESCRIPCION` VARCHAR(450) NULL ,
  `ID_PROPIEDAD` INT NOT NULL ,
  `STATUS` TINYINT(1) NULL ,
  PRIMARY KEY (`ID_CATALOGO_FOTOS`) ,
  INDEX `FK_TMB_PROP_idx` (`ID_PROPIEDAD` ASC) ,
  CONSTRAINT `FK_TMB_PROP`
    FOREIGN KEY (`ID_PROPIEDAD` )
    REFERENCES `mydb`.`PROPIEDAD` (`ID_PROPIEDAD` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
